export const map = [
  "                M                                     ",
  "                MM                                    ",
  "              MM M                                    ",
  "            MM    M                                   ",
  "           M  MM                                      ",
  "     f  ff                                            ",
  "      fffff f                                         ",
  "     ff                                               ",
  "                                                      ",
  "                                                      ",
  "                                                      ",
  "                                                      ",
  "                                                      ",
];
