export const map = [
  "         M       H       ",
  "H     H HMM H H     H    ",
  "     H MMMMHH  p     H   ",
  "  H  MMMrrMM  ppfff f    ",
  "    MMHMMr H ppfffff  ff ",
  " ffH HHH rHH phffffff ff ",
  "ffff f H rrrhpffffhff    ",
  "        ppprpv fwffff    ",
  "          rrhpffffff     ",
  "          r  pppppppppp  ",
  "          rr          pp ",
  "           r           pp",
  "           rrr           ",
  "            frf          ",
  "        fffffwff         ",
  "      ffffwwwwff         ",
  "       ffwwwwff          ",
  "         www             ",
  "          www            ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "f                        ",
];
